---
title: Welcome
author: Sean Warlick
date: '2015-09-16'
categories:
  - R
---  
Welcome to Let's Ask The Data.

I have launched my first website/blog in an endeavour to share my
experience and learning with others doing similar work in the Data
Science and/or Applied Statistic community. I'm plan to use it as a
place to document my adventures exploring and practising new methods or
showcase projects with cool data sets. In doing so, I hope that others
doing similar work can learn from my blog.

So what topics am I going to cover here? Well, it will center around R
and applied statistics. Given the expanding R ecosystem, this is a broad
topic, but there are few topics that have really attracted my interest.
Reproducible research is one topic that I am particularly interested in
and will likely be touched upon in many posts. I also think predictive
modelling and machine learning are cool topics and I am actively seeking
to expand my tool kit in these areas. Recently I've been toying around
with natural language processing, setting up an RStudio server and have
been trying to learn Python, so these topics might also make an
appearance on these digital pages.

Detailed discussions of theory is one thing that will not appear here. I
do firmly believe in theory and will argue very passionately that one
must understand the underlying mathematics, not just how to interpret
the results, of a given method. However, I am not nearly smart enough to
advance the field of mathematical statistics and there are far better
resources than me for the mechanics of a given method. For readers
interested in the theoretical aspects of topics that I discuss, I'll try
to point you in the direction of resources I've found useful and
accessible.
